# iron/go:dev is the alpine image with the go tools added
FROM iron/go:dev
WORKDIR /app

ENV SRC_DIR=/go/src/ok-hockeyapp

ADD . $SRC_DIR
# Build it:
RUN cd $SRC_DIR; go build -o hockeyapp; cp hockeyapp /app/

ENTRYPOINT ["./hockeyapp", "-chat", "CHAT_ID", "-token", "BOT_TOKEN", "-topic", "Version %v (%v)", "-substring", "BUILD_FILTER_STRING"]
